meta_product_name: "Hopla"
meta_title: "Hopla - Redonnons vie à nos commerces de proximité !"
meta_description: "Cherchez les commerces de proximité autour de vous, et découvrez s'ils proposent des évènements ou bon plans !"
meta_image: "cover.png" 

